[remotetimer] fix so it works in all distros
< 2882.6034> [remotetimer][getPage] AttributeError: ''TimerList' object has no attribute 'timerListWidget''
< 2882.6059> Traceback (most recent call last):
< 2882.6065> File "/usr/lib/enigma2/python/Plugins/Extensions/remoteTimer/plugin.py", line 75, in getPage
< 2882.6067> File "/usr/lib/enigma2/python/Plugins/Extensions/remoteTimer/plugin.py", line 145, in _gotPageLoad
< 2882.6072> AttributeError: 'TimerList' object has no attribute 'timerListWidget'

'timerListWidget' only exists in openatv.

https://github.com/oe-alliance/enigma2-plugins/commit/ba84ecb7ce8d35d92557c118e2eea1010bc281da

Tested by Rob