[EPGSearchpli] Merge EPGSearch openPli to reflect past changes in openPli This fixes for example following GS: Traceback (most recent call last):   File "/usr/lib/enigma2/python/Navigation.py", line 135, in dispatchRecordEvent   File "/usr/lib/enigma2/python/Components/Sources/RecordState.py", line 15, in gotRecordEvent   File "/usr/lib/enigma2/python/Plugins/Extensions/EPGSearch/EPGSearch.py", line 107, in buildEPGSearchEntry AttributeError: 'EPGSearchList' object has no attribute 'getClockPixmap'